// <auto-generated />
namespace Service.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EditMachineData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditMachineData));
        
        string IMigrationMetadata.Id
        {
            get { return "202012170302278_Edit Machine Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
